import { app, dialog } from 'electron'
import type { BrowserWindow } from 'electron'
import fs from 'node:fs'
import path from 'node:path'
import type { CliOpenMsg } from '../shared/ipc.js'
import { repoRoot } from './git.js'

export interface CliArgs { dir: string; base?: string; compare?: string }

/** Parse process/second-instance argv. Returns null unless '--cli' is present.
 *  Pure and unit-testable — no Electron, no fs. */
export function parseCliArgs(argv: string[]): CliArgs | null {
  if (!argv.includes('--cli')) return null
  let dir = process.cwd()
  let base: string | undefined
  let compare: string | undefined
  for (let i = 0; i < argv.length; i++) {
    const next = argv[i + 1]
    if (argv[i] === '--dir' && next) { dir = next; i++ }
    else if (argv[i] === '--base' && next) { base = next; i++ }
    else if (argv[i] === '--compare' && next) { compare = next; i++ }
  }
  const out: CliArgs = { dir }
  if (base !== undefined) out.base = base
  if (compare !== undefined) out.compare = compare
  return out
}

/** A pending cli:open captured before any renderer finished loading. */
let pending: CliOpenMsg | null = null

/** Hand the renderer a CliArgs: resolve the repo root, then either send
 *  'cli:open' to a loaded window or stash it for takeCliOpen(). */
export async function handleCliArgs(args: CliArgs, getWindow: () => BrowserWindow | null): Promise<void> {
  const root = await repoRoot(args.dir)
  const msg: CliOpenMsg = root
    ? { repo: root, baseInput: args.base, compareInput: args.compare }
    : { error: `${args.dir} is not inside a git repository` }
  const win = getWindow()
  if (win && !win.webContents.isLoading()) win.webContents.send('cli:open', msg)
  else pending = msg
}

/** Served once to the renderer at boot (Api.takeCliOpen). */
export function takeCliOpen(): CliOpenMsg | null {
  const msg = pending
  pending = null
  return msg
}

/** POSIX-sh shim that opens (or forwards to) the app for a repo directory. */
function shimContent(): string {
  const header = '#!/bin/sh\n# lr — open Local Review for a repository (generated by the app; reinstall via app menu if the app moves)\n'
  const pickDir = 'DIR="$PWD"\nif [ $# -gt 0 ] && [ "${1#-}" = "$1" ]; then DIR="$1"; shift; fi\n'
  if (app.isPackaged) {
    // process.execPath = …/local-review.app/Contents/MacOS/local-review
    const bundle = process.execPath.slice(0, process.execPath.indexOf('.app/') + 4)
    return `${header}${pickDir}exec open -n -a "${bundle}" --args --cli --dir "$DIR" "$@"\n`
  }
  return `${header}${pickDir}exec "${process.execPath}" "${app.getAppPath()}" --cli --dir "$DIR" "$@"\n`
}

/** Install the `lr` shim to ~/.local/bin (fallback /usr/local/bin). On failure,
 *  write the shim to userData and tell the user how to install it manually. */
export function installCli(): { ok: boolean; message: string } {
  const content = shimContent()
  const targets = [
    path.join(app.getPath('home'), '.local', 'bin', 'lr'),
    path.join('/usr', 'local', 'bin', 'lr')
  ]
  const pathDirs = (process.env.PATH ?? '').split(path.delimiter)
  for (const target of targets) {
    try {
      fs.mkdirSync(path.dirname(target), { recursive: true })
      fs.writeFileSync(target, content)
      fs.chmodSync(target, 0o755)
      const dir = path.dirname(target)
      const onPath = pathDirs.includes(dir)
      const note = onPath
        ? `${dir} is on your PATH — run \`lr\` from any repo.`
        : `${dir} is NOT on your PATH. Add it, e.g.\n  echo 'export PATH="${dir}:$PATH"' >> ~/.zshrc`
      return { ok: true, message: `Installed lr to ${target}.\n${note}` }
    } catch {
      // try the next target
    }
  }
  const fallback = path.join(app.getPath('userData'), 'lr-shim.sh')
  try {
    fs.writeFileSync(fallback, content)
    fs.chmodSync(fallback, 0o755)
  } catch { /* even userData failed — the message still points at the content path */ }
  return {
    ok: false,
    message: `Could not write to ~/.local/bin or /usr/local/bin. The shim was saved to\n  ${fallback}\nCopy it somewhere on your PATH, e.g.\n  cp "${fallback}" ~/.local/bin/lr`
  }
}

/** Used by the app-menu item. */
export function installCliWithDialog(): void {
  const res = installCli()
  void dialog.showMessageBox({
    type: res.ok ? 'info' : 'warning',
    title: 'Install Command-Line Tool',
    message: res.ok ? 'lr installed' : 'lr not installed',
    detail: res.message
  })
}
