import { app, dialog } from 'electron'
import type { BrowserWindow } from 'electron'
import fs from 'node:fs'
import path from 'node:path'
import type { CliOpenMsg } from '../shared/ipc.js'
import { repoRoot } from './git.js'

export interface CliArgs {
  dir: string
  base?: string
  /** the compare side — a branch in the current "repo as source of truth" model.
   *  Accepts `--branch` (preferred) or `--compare` (kept for back-compat). */
  compare?: string
  /** open the repo hub (session list) instead of a review */
  hub?: boolean
  /** force a fresh review rather than resuming an existing one for the pair */
  fresh?: boolean
}

/** Parse process/second-instance argv. Returns null unless '--cli' is present.
 *  Pure and unit-testable — no Electron, no fs. */
export function parseCliArgs(argv: string[]): CliArgs | null {
  if (!argv.includes('--cli')) return null
  const opts: Record<string, string> = {}
  let hub = false
  let fresh = false
  for (let i = 0; i < argv.length; i++) {
    const tok = argv[i]
    if (tok === '--hub') { hub = true; continue }
    if (tok === '--new') { fresh = true; continue }
    // `branch` is the preferred name for the compare side; `compare` is the legacy
    // alias. Both land in opts under their own key and are reconciled below.
    for (const name of ['dir', 'base', 'compare', 'branch']) {
      if (tok === `--${name}`) {
        // space form: only consume the next token as the value if it is not
        // itself a flag. A forwarded second-instance argv is canonicalized by
        // Chromium — bare positionals (the repo path) move to the end, so the
        // token after --dir can be an unrelated --switch we must not capture.
        const next = argv[i + 1]
        if (next && !next.startsWith('-')) { opts[name] = next; i++ }
      } else if (tok.startsWith(`--${name}=`)) {
        // attached form survives canonicalization intact — the shim emits this.
        opts[name] = tok.slice(name.length + 3)
      }
    }
  }
  const out: CliArgs = { dir: opts.dir ?? process.cwd() }
  if (opts.base !== undefined) out.base = opts.base
  // explicit --compare wins over --branch when both are somehow present
  const compare = opts.compare ?? opts.branch
  if (compare !== undefined) out.compare = compare
  if (hub) out.hub = true
  if (fresh) out.fresh = true
  return out
}

/** A cli:open captured before the renderer announced readiness. */
let pending: CliOpenMsg | null = null
/** Flips on the renderer's first takeCliOpen() call, which it makes right
 *  after subscribing to onCliOpen — so "ready" exactly tracks "subscribed".
 *  A page load alone is NOT enough: a message sent before React mounts its
 *  listener would be silently dropped. */
let rendererReady = false

/** Hand the renderer a CliArgs: resolve the repo root, then either send
 *  'cli:open' to a loaded window or stash it for takeCliOpen(). */
export async function handleCliArgs(args: CliArgs, getWindow: () => BrowserWindow | null): Promise<void> {
  const root = await repoRoot(args.dir)
  const msg: CliOpenMsg = root
    ? { repo: root, baseInput: args.base, compareInput: args.compare, hub: args.hub, fresh: args.fresh }
    : { error: `${args.dir} is not inside a git repository` }
  const win = getWindow()
  if (rendererReady && win) win.webContents.send('cli:open', msg)
  else pending = msg
}

/** Served once to the renderer at boot (Api.takeCliOpen); marks it ready. */
export function takeCliOpen(): CliOpenMsg | null {
  rendererReady = true
  const msg = pending
  pending = null
  return msg
}

/** POSIX-sh shim that opens (or forwards to) the app for a repo directory. */
function shimContent(): string {
  const header = '#!/bin/sh\n# lr — open Local Review for a repository (generated by the app; reinstall via app menu if the app moves)\n'
  const pickDir = 'DIR="$PWD"\nif [ $# -gt 0 ] && [ "${1#-}" = "$1" ]; then\n  case "$1" in /*) DIR="$1";; *) DIR="$(cd "$1" && pwd)" || exit 1;; esac\n  shift\nfi\n'
  // Emit attached --name=value forms. When the app is already running, the OS
  // forwards argv through Electron's second-instance event, where Chromium
  // canonicalizes the command line — a bare positional (the repo path) gets
  // moved to the end, detaching it from a space-form --dir. Attached forms
  // survive intact, so the running app opens the right repo/refs.
  const normalize = [
    'B=""; C=""; HUB=""; NEW=""',
    'while [ $# -gt 0 ]; do',
    '  case "$1" in',
    '    -h|--help)',
    '      printf "usage: lr [DIR] [--base REF] [--branch BRANCH] [--new] [--hub]\\n"',
    '      printf "  bare: review the current branch  .  --new: fresh review  .  --hub: session list\\n"',
    '      exit 0;;',
    '    --base) if [ $# -ge 2 ]; then B="$2"; shift 2; else shift; fi;;',
    '    --base=*) B="${1#--base=}"; shift;;',
    '    --branch|--compare) if [ $# -ge 2 ]; then C="$2"; shift 2; else shift; fi;;',
    '    --branch=*) C="${1#--branch=}"; shift;;',
    '    --compare=*) C="${1#--compare=}"; shift;;',
    '    --hub) HUB=1; shift;;',
    '    --new) NEW=1; shift;;',
    '    *) shift;;',
    '  esac',
    'done',
    'set -- --cli "--dir=$DIR"',
    '[ -n "$B" ] && set -- "$@" "--base=$B"',
    '[ -n "$C" ] && set -- "$@" "--compare=$C"',
    '[ -n "$HUB" ] && set -- "$@" "--hub"',
    '[ -n "$NEW" ] && set -- "$@" "--new"',
    ''
  ].join('\n')
  if (app.isPackaged) {
    // process.execPath = …/local-review.app/Contents/MacOS/local-review
    const bundle = process.execPath.slice(0, process.execPath.indexOf('.app/') + 4)
    return `${header}${pickDir}${normalize}exec open -n -a "${bundle}" --args "$@"\n`
  }
  return `${header}${pickDir}${normalize}exec "${process.execPath}" "${app.getAppPath()}" "$@"\n`
}

/** Install the `lr` shim to ~/.local/bin (fallback /usr/local/bin). On failure,
 *  write the shim to userData and tell the user how to install it manually. */
export function installCli(): { ok: boolean; message: string } {
  const content = shimContent()
  const targets = [
    path.join(app.getPath('home'), '.local', 'bin', 'lr'),
    path.join('/usr', 'local', 'bin', 'lr')
  ]
  const pathDirs = (process.env.PATH ?? '').split(path.delimiter)
  for (const target of targets) {
    try {
      fs.mkdirSync(path.dirname(target), { recursive: true })
      fs.writeFileSync(target, content)
      try {
        fs.chmodSync(target, 0o755)
      } catch (err) {
        fs.rmSync(target, { force: true }) // don't leave a non-executable shim behind
        throw err
      }
      const dir = path.dirname(target)
      const onPath = pathDirs.includes(dir)
      const note = onPath
        ? `${dir} is on your PATH — run \`lr\` from any repo.`
        : `${dir} is NOT on your PATH. Add it, e.g.\n  echo 'export PATH="${dir}:$PATH"' >> ~/.zshrc`
      return { ok: true, message: `Installed lr to ${target}.\n${note}` }
    } catch {
      // try the next target
    }
  }
  const fallback = path.join(app.getPath('userData'), 'lr-shim.sh')
  try {
    fs.writeFileSync(fallback, content)
    fs.chmodSync(fallback, 0o755)
  } catch { /* even userData failed — the message still points at the content path */ }
  return {
    ok: false,
    message: `Could not write to ~/.local/bin or /usr/local/bin. The shim was saved to\n  ${fallback}\nCopy it somewhere on your PATH, e.g.\n  cp "${fallback}" ~/.local/bin/lr`
  }
}

/** Used by the app-menu item. */
export function installCliWithDialog(): void {
  const res = installCli()
  void dialog.showMessageBox({
    type: res.ok ? 'info' : 'warning',
    title: 'Install Command-Line Tool',
    message: res.ok ? 'lr installed' : 'lr not installed',
    detail: res.message
  })
}
