/* Screenshot seed (dev only): builds a fixture repo + a pre-seeded db with a
 * generated review and two populated chats (the review agent on Claude, plus a
 * second chat switched to Codex). Prints { repo, db, sessionId } as JSON so a
 * launcher can run Electron with LR_DB / LR_OPEN_SESSION / LR_FLOW=chat. */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { makeFixtureRepo } from '../tests/helpers/fixtureRepo'
import { getDiff, resolveRefInput } from '../src/main/git'
import { FakeEngine } from '../src/main/engines/fake'
import { mergeAnnotations } from '../src/main/engines/validate'
import { openDb } from '../src/main/db/db'
import {
  createSession, updateSessionMeta, addIteration, reconcileChats,
  listChatThreads, addChatMessage, setThreadAgent, setThreadEngineSession
} from '../src/main/db/sessions'
import type { RefPair } from '../src/shared/types'

const fx = makeFixtureRepo()
const sk = await getDiff(fx.dir, 'main', 'feature')
const run = new FakeEngine().generateReview({ repo: fx.dir, branch: 'feature', base: 'main', diff: sk, artifacts: [] })
for await (const _ of run.events) { /* drain */ }
const { value, sessionId: engineSession } = await run.result
const { annotations } = mergeAnnotations(sk, value)

const base = await resolveRefInput(fx.dir, 'main')
const compare = await resolveRefInput(fx.dir, 'feature')
const pair: RefPair = {
  base: { kind: base.kind, symbol: base.symbol, anchorSha: base.sha },
  compare: { kind: compare.kind, symbol: compare.symbol, anchorSha: compare.sha }
}

const dbFile = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'lr-shot-')), 'local-review.db')
const { db } = openDb(dbFile)

// review generated by Claude · Opus
const session = createSession(db, fx.dir, pair, { engine: 'claude', model: 'opus' })
updateSessionMeta(db, session.id, {
  engine: 'claude', model: 'opus',
  annotations, title: annotations.title, summary: annotations.summary,
  reviewedAtSha: fx.shas.head, approvedSha: fx.shas.head
})
addIteration(db, session.id, { n: 1, engine: 'claude', sessionId: engineSession, endSha: fx.shas.head, at: 'now' })

// default chats: review (claude/opus) + one empty user chat
reconcileChats(db, session.id)
const chats = listChatThreads(db, session.id)
const reviewChat = chats.find((c) => c.kind === 'review')!
const userChat = chats.find((c) => c.kind === 'user')!

// populate the review chat (resumes the review agent's session — full context)
addChatMessage(db, reviewChat.id, { role: 'user', text: 'Why did you flag the early return in `src/a.ts`?', at: 'now' })
addChatMessage(db, reviewChat.id, {
  role: 'agent', at: 'now', text: [
    'Good question — the flag is about **behavior on the empty input**, not style.',
    '',
    '- Before, the function always returned a number.',
    '- The new guard returns `null`, so callers must handle it.',
    '',
    '```ts',
    'if (!input) return null // new — callers now see null',
    '```',
    '',
    'Only `parseRefInput` calls it today, and it already null-checks, so this is safe.'
  ].join('\n')
})

// second chat: switched to Codex · gpt-5-codex (high) and asked a security question
setThreadAgent(db, userChat.id, { engine: 'codex', model: 'gpt-5-codex', reasoningEffort: 'high' })
setThreadEngineSession(db, userChat.id, 'codex-thread-1')
addChatMessage(db, userChat.id, { role: 'user', text: 'Do a quick security pass on the new branch.', at: 'now' })
addChatMessage(db, userChat.id, {
  role: 'agent', at: 'now', text: [
    '## Security pass',
    '',
    'Nothing high-risk in this diff. Two things worth a glance:',
    '',
    '- `src/b.ts` returns a constant — no input handling, safe.',
    '- The deleted `src/old.ts` had no exported secrets.',
    '',
    'No injection, path, or auth surfaces changed. Looks clean.'
  ].join('\n')
})

console.log(JSON.stringify({ repo: fx.dir, db: dbFile, sessionId: session.id }))
