/* Screenshot seed (dev only): builds a fixture repo + a pre-seeded db with a
 * generated review and two populated chats (the review agent on Claude, plus a
 * second chat switched to Codex). Prints { repo, db, sessionId } as JSON so a
 * launcher can run Electron with LIMN_DB / LIMN_OPEN_SESSION / LIMN_FLOW=chat. */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { makeFixtureRepo, fixtureWrite, fixtureGit } from '../tests/helpers/fixtureRepo'
import { getDiff, resolveRefInput } from '../src/main/git'
import { FakeEngine } from '../src/main/engines/fake'
import { mergeAnnotations } from '../src/main/engines/validate'
import { openDb } from '../src/main/db/db'
import {
  createSession, updateSessionMeta, addIteration, reconcileChats, createChatThread,
  listChatThreads, addChatMessage, setThreadAgent, setThreadEngineSession, upsertComment, setArtifacts
} from '../src/main/db/sessions'
import type { RefPair } from '../src/shared/types'

const fx = makeFixtureRepo()
// recognized-format spec + plan written on the branch (Superpowers convention),
// so the review surfaces the format-flagged artifacts in the diff + sidebar
const SPEC = 'docs/superpowers/specs/2026-06-12-rate-limit-design.md'
const PLAN = 'docs/superpowers/plans/2026-06-12-rate-limit.md'
fixtureWrite(fx.dir, SPEC, '# Rate limiting spec\n\nGoal: protect the API on branch feature.\n\n- requests are capped per client\n- the cap is configurable\n')
fixtureWrite(fx.dir, PLAN, '# Rate limiting plan\n\n1. add a token-bucket limiter\n2. wire it into the request path\n3. expose the cap as config\n')
fixtureGit(fx.dir, 'add', '-A')
fixtureGit(fx.dir, 'commit', '-m', 'spec + plan for rate limiting')
const sk = await getDiff(fx.dir, 'main', 'feature')
const run = new FakeEngine().generateReview({ repo: fx.dir, branch: 'feature', base: 'main', diff: sk, artifacts: [] })
for await (const _ of run.events) { /* drain */ }
const { value, sessionId: engineSession } = await run.result
const { annotations } = mergeAnnotations(sk, value)
// the FakeEngine doesn't emit a planMap; synthesize one so the spec acceptance
// list + plan steps (and the per-step comment affordance) render in the spine.
const firstSection = annotations.sections[0]?.id ?? 's1'
annotations.planMap = {
  acceptance: [
    { text: 'requests are capped per client', met: true },
    { text: 'the cap is configurable', met: 'partial' }
  ],
  steps: [
    { n: 1, text: 'add a token-bucket limiter', sectionId: firstSection, status: 'done' },
    { n: 2, text: 'wire it into the request path', sectionId: firstSection, status: 'changed' },
    { n: 3, text: 'expose the cap as config', sectionId: firstSection, status: 'missing' }
  ],
  deviations: [
    { text: 'the cap was hard-coded to 100 rather than read from config', sectionId: firstSection }
  ]
}

const base = await resolveRefInput(fx.dir, 'main')
const compare = await resolveRefInput(fx.dir, 'feature')
const pair: RefPair = {
  base: { kind: base.kind, symbol: base.symbol, anchorSha: base.sha },
  compare: { kind: compare.kind, symbol: compare.symbol, anchorSha: compare.sha }
}

const dbFile = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'limn-shot-')), 'limn.db')
const { db } = openDb(dbFile)

// review generated by Claude · Opus
const session = createSession(db, fx.dir, pair, { engine: 'claude', model: 'opus' })
updateSessionMeta(db, session.id, {
  engine: 'claude', model: 'opus',
  annotations, title: annotations.title, summary: annotations.summary,
  reviewedAtSha: compare.sha, approvedSha: compare.sha
})
addIteration(db, session.id, { n: 1, engine: 'claude', sessionId: engineSession, endSha: compare.sha, at: 'now' })
setArtifacts(db, session.id, [{ role: 'spec', path: SPEC }, { role: 'plan', path: PLAN }])

// default chats: review (claude/opus, bound to the gen session) + an empty user
// chat. The review thread is now created up front by beginReview, so seed it
// explicitly; reconcileChats backs the companion "New chat".
const reviewChat = createChatThread(db, session.id, { kind: 'review', agent: { engine: 'claude', model: 'opus' }, engineSessionId: engineSession, title: 'Review agent' })
reconcileChats(db, session.id)
const chats = listChatThreads(db, session.id)
const userChat = chats.find((c) => c.kind === 'user')!

// populate the review chat (resumes the review agent's session — full context)
addChatMessage(db, reviewChat.id, { role: 'user', text: 'Why did you flag the early return in `src/a.ts`?', at: 'now' })
addChatMessage(db, reviewChat.id, {
  role: 'agent', at: 'now', text: [
    'Good question — the flag is about **behavior on the empty input**, not style.',
    '',
    '- Before, the function always returned a number.',
    '- The new guard returns `null`, so callers must handle it.',
    '',
    '```ts',
    'if (!input) return null // new — callers now see null',
    '```',
    '',
    'Only `parseRefInput` calls it today, and it already null-checks, so this is safe.'
  ].join('\n'),
  // tool actions: focus + suggest + a comment it left + a comment it resolved
  actions: [
    { kind: 'focus', anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 2, hunkRange: '', lineContent: '' } },
    { kind: 'comment_added', comment: {
      id: 'agent-c1', anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 2, hunkRange: '', lineContent: '' },
      author: 'agent', text: 'guard note', status: 'resolved', replies: [], createdAt: 'now', iteration: 1
    } },
    { kind: 'comment_resolved', commentId: 'user-c1', anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 5, hunkRange: '', lineContent: '' }, verdict: 'addressed', note: 'Confirmed and wired a first use.' },
    { kind: 'review_edited', field: 'summary' },
    { kind: 'suggest_viewed', files: ['src/a.ts'], note: 'You seem to fully understand the guard now.' }
  ]
})

// second chat: switched to Codex · gpt-5.5 (high) and asked a security question
setThreadAgent(db, userChat.id, { engine: 'codex', model: 'gpt-5.5', reasoningEffort: 'high' })
setThreadEngineSession(db, userChat.id, 'codex-thread-1')
addChatMessage(db, userChat.id, { role: 'user', text: 'Do a quick security pass on the new branch.', at: 'now' })
addChatMessage(db, userChat.id, {
  role: 'agent', at: 'now', text: [
    '## Security pass',
    '',
    'Nothing high-risk in this diff. Per-file read:',
    '',
    '| File | Surface | Verdict |',
    '| --- | --- | --- |',
    '| `src/a.ts` | guard + constant | ~~risky~~ *safe* |',
    '| `src/b.ts` | returns a constant | safe |',
    '| `src/old.ts` | **deleted** | no exported secrets |',
    '',
    'Steps I checked, in order:',
    '',
    '1. input handling on the new guard',
    '2. path / injection surfaces',
    '3. auth boundaries',
    '',
    'No injection, path, or auth surfaces changed — see the [OWASP cheatsheet](https://cheatsheetseries.owasp.org/) for the checklist I follow. Looks clean.'
  ].join('\n')
})

// agent-authored comment (identity → the review agent's chat) + a user comment
// the agent replied to and resolved (the round-trip with a verdict badge).
upsertComment(db, session.id, {
  id: 'agent-c1',
  anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 2, hunkRange: '@@ -1,4 +1,5 @@', lineContent: '  return 2' },
  author: 'agent', agentRef: { engine: 'claude', model: 'opus' }, threadId: reviewChat.id,
  text: 'Heads up: this guard makes the return type `number | null`, so the two callers must null-check.',
  status: 'resolved', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-c1',
  anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 5, hunkRange: '@@ -1,4 +1,5 @@', lineContent: 'export const J = 20' },
  author: 'user', text: 'Is this constant actually used anywhere yet?',
  status: 'resolved',
  resolution: { verdict: 'addressed', note: 'Confirmed and wired a first use.', commit: 'a1b2c3d' },
  replies: [{
    author: 'agent', text: 'Good catch — it was dead. I referenced it from `b.ts` so it is exercised now.',
    at: 'now', agentRef: { engine: 'claude', model: 'opus' }, threadId: reviewChat.id
  }],
  createdAt: 'now', iteration: 1
})

// a still-queued comment, so the batch CTA shows and a real batch run has work
upsertComment(db, session.id, {
  id: 'user-q1',
  anchor: { kind: 'diff', file: 'src/a.ts', side: 'new', line: 4, hunkRange: '@@ -1,4 +1,5 @@', lineContent: 'export const K = 10' },
  author: 'user', text: 'Can you add a short test covering K?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})

// comments on the non-diff agentic-review elements — these exercise the new
// per-element commenting (summary / section diagram / file / plan step / doc block).
upsertComment(db, session.id, {
  id: 'user-summary1', anchor: { kind: 'summary' },
  author: 'user', text: 'Please call out the rollout + runbook impact in this summary.',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-diagram1', anchor: { kind: 'section', sectionId: firstSection, part: 'diagram' },
  author: 'user', text: 'The diagram should show the limiter sitting before auth, not after it.',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-file1', anchor: { kind: 'file', file: 'src/a.ts' },
  author: 'user', text: 'Whole-file note: can we split the limiter from the request-path wiring?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-step1', anchor: { kind: 'plan-step', stepN: 1 },
  author: 'user', text: 'Should step 1 use a sliding window instead of a token bucket?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-art1', anchor: { kind: 'artifact', path: PLAN, line: 3, lineContent: '1. add a token-bucket limiter' },
  author: 'user', text: 'Note the default bucket size right here so reviewers see the chosen cap.',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})

// follow-up pass: comment on the title, an acceptance criterion, a deviation, a
// hunk, and text selections in the narration + the doc (proves "comment on
// everything" + text-selection commenting).
const narration = annotations.sections[0]?.what ?? 'the narration'
const narrationQuote = narration.split(' ').slice(0, 4).join(' ')
upsertComment(db, session.id, {
  id: 'user-title1', anchor: { kind: 'title' },
  author: 'user', text: 'Can the title say “per-client” so it’s unambiguous?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-acc1', anchor: { kind: 'acceptance', index: 1 },
  author: 'user', text: 'How is “configurable” surfaced — env var or config file?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-dev1', anchor: { kind: 'deviation', index: 0 },
  author: 'user', text: 'Please pull the cap from config before we merge, as the plan said.',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-sel-sec', anchor: { kind: 'selection', scope: { region: 'section', sectionId: firstSection }, quote: narrationQuote, prefix: '', suffix: '' },
  author: 'user', text: 'Selected the narration — is this the intended behavior on empty input?',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})
upsertComment(db, session.id, {
  id: 'user-sel-doc', anchor: { kind: 'selection', scope: { region: 'artifact', path: PLAN }, quote: 'token-bucket limiter', prefix: 'add a ', suffix: '' },
  author: 'user', text: 'Selected “token-bucket limiter” — consider a sliding window instead.',
  status: 'queued', replies: [], createdAt: 'now', iteration: 1
})

// extra sessions so the repo hub list + the review's session dropdown have content
// (multiple reviews of the same branch, latest on top)
const s2 = createSession(db, fx.dir, {
  base: { kind: 'commit', symbol: 'HEAD~1', anchorSha: fx.shas.firstFeature },
  compare: { kind: 'branch', symbol: 'feature', anchorSha: compare.sha }
}, { engine: 'codex', model: 'gpt-5.5', reasoningEffort: 'high' })
updateSessionMeta(db, s2.id, { title: 'Incremental pass since last commit' })
const s3 = createSession(db, fx.dir, {
  base: { kind: 'branch', symbol: 'main', anchorSha: base.sha },
  compare: { kind: 'branch', symbol: 'feature', anchorSha: compare.sha }
}, { engine: 'claude', model: 'sonnet' })
updateSessionMeta(db, s3.id, { title: 'First look' })

console.log(JSON.stringify({ repo: fx.dir, db: dbFile, sessionId: session.id, reviewChat: reviewChat.id, userChat: userChat.id }))
